ValueSet: DVCVaccines
Id: DVC-vaccineClassification
Title : "DVC - Vaccines"
Description: "This value set includes codes from ICD"


* $ICD11#XM29K4	"Cholera vaccines"
* $ICD11#XM3Z26	"Cholera, inactivated, whole cell vaccines"
* $ICD11#XM72A0	"Cholera, live attenuated vaccines"
* $ICD11#XM1FT6	"Cholera, combinations with typhoid vaccine, inactivated, whole cell vaccines"
* $ICD11#XM11V3	"Haemophilus influenzae B vaccines"
* $ICD11#XM6RG9	"Hib, purified antigen conjugated vaccines"
* $ICD11#XM7F70	"Hib, combinations with toxoids vaccines"
* $ICD11#XM81F7	"Hib, combinations with pertussis and toxoids vaccines"
* $ICD11#XM0X86	"Hib, combinations with meningococcus C, conjugated vaccines"
* $ICD11#XM1LX9	"Diphtheria, hemophilus influenzae B, pertussis, poliomyelitis, tetanus vaccines"
* $ICD11#XM01H1	"Hemophilus influenzae B and poliomyelitis vaccines"
* $ICD11#XM32L7	"Hemophilus influenzae B and hepatitis B vaccines"
* $ICD11#XM7JP3	"Diphtheria, hemophilus influenzae B, pertussis, tetanus, hepatitis B vaccines"
* $ICD11#XM5XP9	"Diphtheria, hemophilus influenzae B, pertussis, tetanus-hepatitis B, meningococcus A + C vaccines"
* $ICD11#XM21E6	"Diphtheria tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM84S1	"Diphtheria, hepatitis B, tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM2WV4	"Meningococcal vaccines"
* $ICD11#XM92B2	"Meningococcal monovalent purified polysaccharides antigen vaccines"
* $ICD11#XM5LC2	"Meningococcal polyvalent purified polysaccharides antigen vaccines"
* $ICD11#XM3T39	"Meningococcus A, C, bivalent purified polysaccharides antigen vaccines"
* $ICD11#XM2AR0	"Meningococcus A, C, Y, W-135, tetravalent purified polysaccharides antigen vaccines"
* $ICD11#XM2EH7	"Meningococcus A, C, Y, W-135, tetravalent purified polysaccharides antigen conjugated vaccines"
* $ICD11#XM18Y8	"Meningococcus C, purified polysaccharides antigen conjugated vaccines"
* $ICD11#XM2280	"Meningococcus A, purified polysaccharides antigen conjugated vaccines"
* $ICD11#XM9GJ1	"Meningococcus B, outer membrane vesicle vaccines"
* $ICD11#XM1X81	"Meningococcus B, multicomponent vaccines"
* $ICD11#XM37L5	"Meningococcus A, purified polysaccharides antigen vaccines"
* $ICD11#XM43M9	"Pertussis vaccines"
* $ICD11#XM45L8	"Pertussis, inactivated, whole cell vaccines"
* $ICD11#XM62J1	"Pertussis, purified antigen vaccines"
* $ICD11#XM2TK2	"Pertussis, inactivated, whole cell, combinations with toxoids vaccines"
* $ICD11#XM4082	"Pertussis, purified antigen, combinations with toxoids vaccines"
* $ICD11#XM2CV8	"Vaccines pertussis with diphtheria"
* $ICD11#XM31Q8	"Tetanus, diphtheria, acellular pertussis vaccines"
* $ICD11#XM1PB8	"Triple vaccines DPT"
* $ICD11#XM9ZL9	"Pertussis vaccines (with diphtheria toxoid) (with tetanus toxoid)"
* $ICD11#XM9YH9	"Diphtheria toxoid with tetanus toxoid with pertussis component vaccines"
* $ICD11#XM46V1	"Diphtheria vaccines combination including pertussis"
* $ICD11#XM09Q7	"Diphtheria, pertussis, poliomyelitis, tetanus vaccines"
* $ICD11#XM41N3	"Diphtheria, hepatitis B, pertussis, tetanus vaccines"
* $ICD11#XM0LT9	"Diphtheria, pertussis, poliomyelitis, tetanus, hepatitis B vaccines"
* $ICD11#XM9JP8	"Diphtheria, tetanus, acellular pertussis, inactivated polio virus vaccines"
* $ICD11#XM9EM7	"Pneumococcal vaccines"
* $ICD11#XM9G97	"Pneumococcal conjugate (13-valent) vaccines"
* $ICD11#XM2249	"Pneumococcal polysaccharide 23-valent vaccines"
* $ICD11#XM91D7	"Pneumococcus, purified polysaccharides antigen vaccines"
* $ICD11#XM96S7	"Pneumococcus, purified polysaccharides antigen conjugated vaccines"
* $ICD11#XM4R39	"Pneumococcus purified polysaccharides antigen and Haemophilus influenzae, conjugated vaccines"
* $ICD11#XM5L44	"Tetanus vaccines"
* $ICD11#XM29H5	"Tetanus toxoid vaccines"
* $ICD11#XM1G86	"Tetanus toxoid, combinations with diphtheria toxoid vaccines"
* $ICD11#XM9AK2	"Tetanus toxoid, combinations with tetanus immunoglobulin vaccines"
* $ICD11#XM32Q5	"Tetanus and diphtheria vaccines"
* $ICD11#XM4039	"Vaccines diphtheria with tetanus"
* $ICD11#XM8XH5	"Tetanus toxoid or vaccines toxoid with diphtheria toxoid"
* $ICD11#XM8AW1	"Diphtheria, poliomyelitis, tetanus vaccines"
* $ICD11#XM9744	"Diphtheria, rubella, tetanus vaccines"
* $ICD11#XM3G68	"Diphtheria, hepatitis B, tetanus vaccines"
* $ICD11#XM8BU8	"Typhoid vaccines"
* $ICD11#XM33K4	"Typhoid, oral, live attenuated vaccines"
* $ICD11#XM89G3	"Typhoid, inactivated, whole cell vaccines"
* $ICD11#XM3SF6	"Typhoid, purified polysaccharide antigen vaccines"
* $ICD11#XM9UB1	"Typhoid-paratyphoid vaccines"
* $ICD11#XM3VD2	"Vaccines TAB"
* $ICD11#XM95H3	"Paratyphoid vaccines"
* $ICD11#XM3JA6	"Typhoid, hepatitis A vaccines"
* $ICD11#XM8ZX8	"Plague vaccines"
* $ICD11#XM3796	"Plague, inactivated, whole cell vaccines"
* $ICD11#XM9SW5	"Vaccines bacterial with other bacterial component"
* $ICD11#XM91J8	"Vaccines rickettsial"
* $ICD11#XM3JJ2	"Typhus (exanthematicus) vaccines"
* $ICD11#XM2NU8	"Typhus exanthematicus, inactivated, whole cell vaccines"
* $ICD11#XM4F19	"Vaccines rickettsial with bacterial component"
* $ICD11#XM0E84	"Rocky Mountain spotted fever vaccines"
* $ICD11#XM5926	"Vaccines bacterial mixed, not elsewhere classified"
* $ICD11#XM8NU9	"Anthrax vaccines"
* $ICD11#XM2C05	"Anthrax antigen vaccines"
* $ICD11#XM7PB3	"Brucellosis vaccines"
* $ICD11#XM7RX8	"Brucella antigen vaccines"
* $ICD11#XM8AW3	"Diphtheria vaccines"
* $ICD11#XM86V7	"Diphtheria toxoid vaccines"
* $ICD11#XM39K8	"Diphtheria vaccines combination without pertussis"
* $ICD11#XM8YP9	"Diphtheria vaccines combination"
* $ICD11#XM4639	"Tuberculosis vaccines"
* $ICD11#XM8142	"Tuberculosis, live attenuated vaccines"
* $ICD11#XM68M6	"COVID-19 vaccines"
* $ICD11#XM1NL1	"COVID-19 vaccines, inactivated virus"
* $ICD11#XM7HT3	"CoronaVac®"
* $ICD11#XM8866	"Covilo"
* $ICD11#XM9TQ1	"KCONVAC"
* $ICD11#XM1G90	"Covaxin"
* $ICD11#XM85P5	"Covi-Vac"
* $ICD11#XM9FQ7	"Hayat-Vax"
* $ICD11#XM97N6	"QazVac"
* $ICD11#XM2YG8	"COVIran Barekat"
* $ICD11#XM0K39	"Covidful"
* $ICD11#XM0J98	"FAKHRAVAC (MIVAC)"
* $ICD11#XM1FB4	"Inactivated SARS-CoV-2 vaccine"
* $ICD11#XM86F7	"Turkovac"
* $ICD11#XM42N8	"VLA2001"
* $ICD11#XM5DF6	"COVID-19 vaccines, live attenuated virus"
* $ICD11#XM9QW8	"COVID-19 vaccines, non-replicating viral vector"
* $ICD11#XM4YL8	"COVID-19 Vaccine AstraZeneca - Vaxzevria"
* $ICD11#XM97T2	"Covishield®"
* $ICD11#XM6QV1	"COVID-19 Vaccine Janssen"
* $ICD11#XM1AG7	"Convidecia"
* $ICD11#XM5QM6	"Sputnik-Light"
* $ICD11#XM4T09	"Convidecia Air"
* $ICD11#XM2LP0	"Convidecia Air XBB1.5."
* $ICD11#XM6Z24	"Gam-COVID-Vac (intranasal)"
* $ICD11#XM4PM4	"Gam-COVID-Vac-M"
* $ICD11#XM5309	"iNCOVACC"
* $ICD11#XM4N49	"Jcovden"
* $ICD11#XM37C0	"Sputnik-V"
* $ICD11#XM0CX4	"COVID-19 vaccines, replicating viral vector"
* $ICD11#XM5BL0	"DelNS1-2019-nCoV-RBD-OPT1"
* $ICD11#XM5JC5	"COVID-19 vaccines, virus protein subunit"
* $ICD11#XM3CT4	"Zifivax"
* $ICD11#XM8T18	"Abdala"
* $ICD11#XM3PG0	"Soberana-02"
* $ICD11#XM4EC8	"MVC COVID-19"
* $ICD11#XM6SZ8	"EpiVacCorona"
* $ICD11#XM0RV9	"Soberana Plus"
* $ICD11#XM3SK8	"Aurora-CoV"
* $ICD11#XM9P21	"SpikoGen"
* $ICD11#XM9T65	"NUVAXOVID"
* $ICD11#XM9N08	"Razi COV PARS"
* $ICD11#XM6790	"Bimervax"
* $ICD11#XM8R60	"Bivalent Omicron"
* $ICD11#XM63N7	"Corbevax"
* $ICD11#XM2NP9	"Coviccine"
* $ICD11#XM0E93	"Coviccine Trivalent (XBB.1.5+BA.5+Delta)"
* $ICD11#XM85Q5	"Covovax"
* $ICD11#XM85Q8	"EuCorVac-19"
* $ICD11#XM7E37	"Indovac"
* $ICD11#XM7P85	"Noora"
* $ICD11#XM2FM2	"NUVAXOVID XBB1.5."
* $ICD11#XM97Q5	"PastoCovac"
* $ICD11#XM8BU1	"PastoCovac Plus"
* $ICD11#XM9P29	"Recombinant SARS-CoV-2 Vaccine (CHO Cell)"
* $ICD11#XM5YS2	"SARS-COV-2 Bivalent"
* $ICD11#XM8ME2	"SCB-2019"
* $ICD11#XM71X6	"SCTV01C"
* $ICD11#XM62V8	"SKYCovione"
* $ICD11#XM8267	"Tetravalent SCTV01E"
* $ICD11#XM6WB0	"V-01"
* $ICD11#XM9ZB6	"Vidprevtyn Beta"
* $ICD11#XM1J92	"COVID-19 vaccines, virus like particle"
* $ICD11#XM0BS6	"Covifenz"
* $ICD11#XM6AT1	"COVID-19 vaccines, DNA based"
* $ICD11#XM52P3	"ZyCov-D"
* $ICD11#XM0GQ8	"COVID-19 vaccines, RNA based"
* $ICD11#XM8NQ0	"Comirnaty®"
* $ICD11#XM3DT5	"COVID-19 Vaccine Moderna - Spikevax"
* $ICD11#XM5E97	"AWcorna"
* $ICD11#XM1CQ8	"Comirnaty Bivalent Original/Omicron BA.1"
* $ICD11#XM5U85	"Comirnaty Bivalent Original/Omicron BA.4/BA.5"
* $ICD11#XM7U45	"Comirnaty XBB.1.5."
* $ICD11#XM6HM3	"Daichirona"
* $ICD11#XM15E9	"Duentai"
* $ICD11#XM2708	"Duentai Bivalent (XBB.1.5+BQ.1)"
* $ICD11#XM3X29	"Gemcovac-19"
* $ICD11#XM8FH6	"Gemcovac-OM"
* $ICD11#XM6FF0	"KOSTAIVE"
* $ICD11#XM0QH5	"COVID-19 Vaccine Moderna - Spikevax Bivalent Original/Omicron BA.1"
* $ICD11#XM3984	"COVID-19 Vaccine Moderna - Spikevax Bivalent Original/Omicron BA.4/BA.5"
* $ICD11#XM21B8	"COVID-19 Vaccine Moderna - Spikevax XBB1.5."
* $ICD11#XM38G7	"Dengue vaccines"
* $ICD11#XM7P50	"Ebola vaccines"
* $ICD11#XM0RC1	"Encephalitis vaccines"
* $ICD11#XM8MP6	"Encephalitis, tick borne, inactivated, whole virus"
* $ICD11#XM0LB5	"Encephalitis, Japanese, inactivated, whole virus"
* $ICD11#XM47S0	"Encephalitis, Japanese, live attenuated"
* $ICD11#XM1LR5	"Influenza vaccines"
* $ICD11#XM8857	"Influenza vaccines, inactivated, whole virus"
* $ICD11#XM5V64	"Influenza vaccines, live attenuated"
* $ICD11#XM8MP2	"Influenza vaccines, inactivated, split virus or surface antigen"
* $ICD11#XM9E16	"Influenza vaccines, virus like particle"
* $ICD11#XM33X8	"Influenza, purified antigen"
* $ICD11#XM6LL6	"Hepatitis vaccines"
* $ICD11#XM9V38	"Hepatitis B, purified antigen"
* $ICD11#XM2A12	"Hepatitis A, inactivated, whole virus"
* $ICD11#XM03Y7	"Combinations hepatitis vaccines"
* $ICD11#XM28X5	"Measles vaccines"
* $ICD11#XM8L15	"Measles, live attenuated"
* $ICD11#XM9439	"Measles, combinations with mumps, live attenuated"
* $ICD11#XM8TF3	"Measles, combinations with mumps and rubella, live attenuated"
* $ICD11#XM21H2	"Measles, combinations with rubella, live attenuated"
* $ICD11#XM4AJ8	"Measles, combinations with mumps, rubella and varicella, live attenuated"
* $ICD11#XM1131	"Mumps vaccines"
* $ICD11#XM2340	"Mumps, live attenuated"
* $ICD11#XM0N50	"Poliomyelitis vaccines"
* $ICD11#XM4KG4	"Orimune"
* $ICD11#XM1Y59	"Vaccine sabin oral"
* $ICD11#XM2KH7	"Diplovax"
* $ICD11#XM0VX8	"Poliomyelitis oral, monovalent live attenuated"
* $ICD11#XM0KZ1	"Poliomyelitis oral, trivalent, live attenuated"
* $ICD11#XM79H3	"Poliomyelitis oral, bivalent, live attenuated"
* $ICD11#XM5V19	"Poliomyelitis, trivalent, inactivated, whole virus"
* $ICD11#XM1CE0	"Rotavirus diarrhoea vaccines"
* $ICD11#XM4GV0	"Rota virus, live attenuated"
* $ICD11#XM4VG1	"Rota virus, pentavalent, live, reassorted"
* $ICD11#XM7PP1	"Rubella vaccines"
* $ICD11#XM9PS9	"Rubella, live attenuated"
* $ICD11#XM3B09	"Rubella, combinations with mumps, live attenuated"
* $ICD11#XM8DG3	"Varicella zoster vaccines"
* $ICD11#XM0NS8	"Varicella, live attenuated"
* $ICD11#XM1SS1	"Zoster, live attenuated"
* $ICD11#XM9QP0	"Papillomavirus vaccines"
* $ICD11#XM1821	"Papillomavirus (human types 6,11,16,18)"
* $ICD11#XM9BT4	"Papillomavirus (human types 16,18)"
* $ICD11#XM5CE9	"Papillomavirus (human types 6,11,16,18,31,33,45,52,58)"
* $ICD11#XM95R0	"Smallpox vaccine"
* $ICD11#XM6T09	"Rabies vaccines"
* $ICD11#XM7BE8	"Rabies, inactivated, whole virus"
* $ICD11#XM02Y0	"Respiratory syncytial virus vaccines"
* $ICD11#XM69P6	"Synagis"
* $ICD11#XM0N24	"Yellow fever vaccines"
* $ICD11#XM3418	"Yellow fever, live attenuated"