ValueSet: DVCVaccines
Id: DVC-vaccineClassification
Title : "DVC - Vaccines"
Description: "This value set includes codes from ICF"
Alias: $ICD11 = http://hl7.org/fhir/sid/icd-11


* $ICD11#XM4639	"Tuberculosis vaccines"
* $ICD11#XM8142	"Tuberculosis, live attenuated vaccines Index term: BCG vaccine"
* $ICD11#XM3Z26	" Cholera, inactivated, whole cell vaccines"
* $ICD11#XM72A0	" Cholera, live attenuated vaccines"
* $ICD11#XM1FT6	" Cholera, combinations with typhoid vaccine, inactivated, whole cell vaccines"
* $ICD11#XM8AW3	" Diphtheria vaccines"
* $ICD11#XM9744	" Diphtheria, rubella, tetanus vaccines"
* $ICD11#XM31Q8	" Tetanus, diphtheria, acellular pertussis"
* $ICD11#XM8AW1	" Diphtheria, poliomyelitis, tetanus vaccines"
* $ICD11#XM09Q7	" Diphtheria, pertussis, poliomyelitis, tetanus vaccines"
* $ICD11#XM41N3	" Diphtheria, hepatitis B, pertussis, tetanus vaccines"
* $ICD11#XM1LX9	" Diphtheria, hemophilus influenzae B, pertussis, poliomyelitis, tetanus vaccines"
* $ICD11#XM29K4	" Cholera vaccines"
* $ICD11#XM3G68	" Diphtheria, hepatitis B, tetanus vaccines"
* $ICD11#XM0LT9	" Diphtheria, pertussis, poliomyelitis, tetanus, hepatitis B vaccines"
* $ICD11#XM7JP3	" Diphtheria, hemophilus influenzae B, pertussis, tetanus, hepatitis B vaccines"
* $ICD11#XM5XP9	" Diphtheria, hemophilus influenzae B, pertussis, tetanus-hepatitis B, meningococcus A + C vaccines"
* $ICD11#XM1G86	" Tetanus toxoid, combinations with diphtheria toxoid vaccines"
* $ICD11#XM32Q5	" Tetanus and diphtheria vaccines"
* $ICD11#XM2CV8	" Vaccines pertussis with diphtheria"
* $ICD11#XM21E6	" Diphtheria tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM84S1	" Diphtheria, hepatitis B, tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM9JP8	" Diphtheria, tetanus, acellular pertussis, inactivated polio virus vaccines"
* $ICD11#XM46V1	" Diphtheria vaccines combination including pertussis"
* $ICD11#XM4039	" Vaccines diphtheria with tetanus"
* $ICD11#XM11V3	" Haemophilus influenzae B vaccines"
* $ICD11#XM1LX9	" Diphtheria, hemophilus influenzae B, pertussis, poliomyelitis, tetanus vaccines"
* $ICD11#XM01H1	" Hemophilus influenzae B and poliomyelitis vaccines"
* $ICD11#XM32L7	" Hemophilus influenzae B and hepatitis B vaccines"
* $ICD11#XM7JP3	" Diphtheria, hemophilus influenzae B, pertussis, tetanus, hepatitis B vaccines"
* $ICD11#XM5XP9	" Diphtheria, hemophilus influenzae B, pertussis, tetanus-hepatitis B, meningococcus A + C vaccines"
* $ICD11#XM21E6	" Diphtheria tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM84S1	" Diphtheria, hepatitis B, tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM6LL6	" Hepatitis vaccines"
* $ICD11#XM2A12	" Hepatitis A, inactivated, whole virus"
* $ICD11#XM3JA6	" Typhoid, hepatitis A vaccines"
* $ICD11#XM03Y7	" Combinations hepatitis vaccines"
* $ICD11#XM9V38	" Hepatitis B, purified antigen"
* $ICD11#XM3G68	" Diphtheria, hepatitis B, tetanus vaccines"
* $ICD11#XM32L7	" Hemophilus influenzae B and hepatitis B vaccines"
* $ICD11#XM7JP3	" Diphtheria, hemophilus influenzae B, pertussis, tetanus, hepatitis B vaccines"
* $ICD11#XM0LT9	" Diphtheria, pertussis, poliomyelitis, tetanus, hepatitis B vaccines"
* $ICD11#XM5XP9	" Diphtheria, hemophilus influenzae B, pertussis, tetanus-hepatitis B, meningococcus A + C vaccines"
* $ICD11#XM84S1	" Diphtheria, hepatitis B, tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM9QP0	" Papillomavirus vaccine"
* $ICD11#XM1821	" Papillomavirus (human types 6,11,16,18)"
* $ICD11#XM9BT4	" Papillomavirus (human types 16,18)"
* $ICD11#XM5CE9	" Papillomavirus (human types 6,11,16,18,31,33,45,52,58)"
* $ICD11#XM0LB5	" Encephalitis, Japanese, inactivated, whole virus"
* $ICD11#XM47S0	" Encephalitis, Japanese, live attenuated"
* $ICD11#XM28X5	" Measles vaccines"
* $ICD11#XM8L15	" Measles, live attenuated"
* $ICD11#XM8TF3	" Measles, combinations with mumps and rubella, live attenuated"
* $ICD11#XM21H2	" Measles, combinations with rubella, live attenuated"
* $ICD11#XM4AJ8	" Measles, combinations with mumps, rubella and varicella, live attenuated"
* $ICD11#XM9439	" Measles, combinations with mumps, live attenuated"
* $ICD11#XM2WV4	" Meningococcal vaccines"
* $ICD11#XM92B2	" Meningococcal monovalent purified polysaccharides antigen vaccines"
* $ICD11#XM5LC2	" Meningococcal polyvalent purified polysaccharides antigen vaccines"
* $ICD11#XM18Y8	" Meningococcus C, purified polysaccharides antigen conjugated vaccines"
* $ICD11#XM2280	" Meningococcus A, purified polysaccharides antigen conjugated vaccines"
* $ICD11#XM9GJ1	" Meningococcus B, outer membrane vesicle vaccines"
* $ICD11#XM1X81	" Meningococcus B, multicomponent vaccines"
* $ICD11#XM37L5	" Meningococcus A, purified polysaccharides antigen vaccines"
* $ICD11#XM1131	" Mumps vaccine"
* $ICD11#XM2340	" Mumps, live attenuated"
* $ICD11#XM4AJ8	" Measles, combinations with mumps, rubella and varicella, live attenuated"
* $ICD11#XM9439	" Measles, combinations with mumps, live attenuated"
* $ICD11#XM3B09	" Rubella, combinations with mumps, live attenuated"
* $ICD11#XM8TF3	" Measles, combinations with mumps and rubella, live attenuated"
* $ICD11#XM43M9 " Pertussis vaccines"
* $ICD11#XM45L8	" Pertussis, inactivated, whole cell vaccines"
* $ICD11#XM62J1	" Pertussis, purified antigen vaccines"
* $ICD11#XM2TK2	" Pertussis, inactivated, whole cell, combinations with toxoids vaccines"
* $ICD11#XM4082	" Pertussis, purified antigen, combinations with toxoids vaccines"
* $ICD11#XM2CV8	" Vaccines pertussis with diphtheria"
* $ICD11#XM1LX9	" Diphtheria, hemophilus influenzae B, pertussis, poliomyelitis, tetanus vaccines"
* $ICD11#XM7JP3	" Diphtheria, hemophilus influenzae B, pertussis, tetanus, hepatitis B vaccines"
* $ICD11#XM41N3	" Diphtheria, hepatitis B, pertussis, tetanus vaccines"
* $ICD11#XM09Q7	" Diphtheria, pertussis, poliomyelitis, tetanus vaccines"
* $ICD11#XM0LT9	" Diphtheria, pertussis, poliomyelitis, tetanus, hepatitis B vaccines"
* $ICD11#XM5XP9	" Diphtheria, hemophilus influenzae B, pertussis, tetanus-hepatitis B, meningococcus A + C vaccines"
* $ICD11#XM31Q8	" Tetanus, diphtheria, acellular pertussis vaccines"
* $ICD11#XM46V1	" Diphtheria vaccines combination including pertussis"
* $ICD11#XM21E6	" Diphtheria tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM84S1	" Diphtheria, hepatitis B, tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM9JP8	" Diphtheria, tetanus, acellular pertussis, inactivated polio virus vaccines"
* $ICD11#XM9EM7	" Pneumococcal vaccines"
* $ICD11#XM9G97	" Pneumococcal conjugate (13-valent) vaccines"
* $ICD11#XM2249	" Pneumococcal polysaccharide 23-valent vaccines"
* $ICD11#XM91D7	" Pneumococcus, purified polysaccharides antigen vaccines"
* $ICD11#XM96S7	" Pneumococcus, purified polysaccharides antigen conjugated vaccines"
* $ICD11#XM4R39	" Pneumococcus purified polysaccharides antigen and Haemophilus influenzae, conjugated vaccines"
* $ICD11#XM0N50	" Poliomyelitis vaccines"
* $ICD11#XM1LX9	" Diphtheria, hemophilus influenzae B, pertussis, poliomyelitis, tetanus vaccines"
* $ICD11#XM09Q7	" Diphtheria, pertussis, poliomyelitis, tetanus vaccines"
* $ICD11#XM0LT9	" Diphtheria, pertussis, poliomyelitis, tetanus, hepatitis B vaccines"
* $ICD11#XM8AW1	" Diphtheria, poliomyelitis, tetanus vaccines"
* $ICD11#XM01H1	" Hemophilus influenzae B and poliomyelitis vaccines"
* $ICD11#XM21E6	" Diphtheria tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM84S1	" Diphtheria, hepatitis B, tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM9JP8	" Diphtheria, tetanus, acellular pertussis, inactivated polio virus vaccines"
* $ICD11#XM5V19	" Poliomyelitis, trivalent, inactivated, whole virus"
* $ICD11#XM8AW1	" Diphtheria, poliomyelitis, tetanus vaccines"
* $ICD11#XM09Q7	" Diphtheria, pertussis, poliomyelitis, tetanus vaccines"
* $ICD11#XM01H1	" Hemophilus influenzae B and poliomyelitis vaccines"
* $ICD11#XM84S1	" Diphtheria, hepatitis B, tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM0LT9	" Diphtheria, pertussis, poliomyelitis, tetanus, hepatitis B vaccines"
* $ICD11#XM1LX9	" Diphtheria, hemophilus influenzae B, pertussis, poliomyelitis, tetanus vaccines"
* $ICD11#XM21E6	" Diphtheria tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM9JP8	" Diphtheria, tetanus, acellular pertussis, inactivated polio virus vaccines"
* $ICD11#XM79H3	" Poliomyelitis oral, bivalent, live attenuated"
* $ICD11#XM0VX8	" Poliomyelitis oral, monovalent live attenuated"
* $ICD11#XM0KZ1	" Poliomyelitis oral, trivalent, live attenuated"
* $ICD11#XM0VX8	" Poliomyelitis oral, monovalent live attenuated"
* $ICD11#XM79H3	" Poliomyelitis oral, bivalent, live attenuated"
* $ICD11#XM0KZ1	" Poliomyelitis oral, trivalent, live attenuated"
* $ICD11#XM5V19	" Poliomyelitis, trivalent, inactivated, whole virus"
* $ICD11#XM84S1	" Diphtheria, hepatitis B, tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM21E6	" Diphtheria tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM9JP8	" Diphtheria, tetanus, acellular pertussis, inactivated polio virus vaccines"
* $ICD11#XM6T09	" Rabies vaccine"
* $ICD11#XM7BE8	" Rabies, inactivated, whole virus"
* $ICD11#XM1CE0	" Rotavirus diarrhoea vaccines"
* $ICD11#XM4GV0	" Rota virus, live attenuated"
* $ICD11#XM4VG1	" Rota virus, pentavalent, live, reassorted"
* $ICD11#XM7PP1	" Rubella vaccine"
* $ICD11#XM9PS9	" Rubella, live attenuated"
* $ICD11#XM3B09	" Rubella, combinations with mumps, live attenuated"
* $ICD11#XM9744	" Diphtheria, rubella, tetanus vaccines"
* $ICD11#XM8TF3	" Measles, combinations with mumps and rubella, live attenuated"
* $ICD11#XM21H2	" Measles, combinations with rubella, live attenuated"
* $ICD11#XM4AJ8	" Measles, combinations with mumps, rubella and varicella, live attenuated"
* $ICD11#XM21H2	" Measles, combinations with rubella, live attenuated"
* $ICD11#XM8TF3	" Measles, combinations with mumps and rubella, live attenuated"
* $ICD11#XM4AJ8	" Measles, combinations with mumps, rubella and varicella, live attenuated"
* $ICD11#XM1LR5	" Influenza vaccines"
* $ICD11#XM8857	" Influenza vaccine, inactivated, whole virus"
* $ICD11#XM5V64	" Influenza vaccines, live attenuated"
* $ICD11#XM8MP2	" Influenza vaccines, inactivated, split virus or surface antigen"
* $ICD11#XM9E16	" Influenza vaccines, virus like particle"
* $ICD11#XM33X8	" Influenza, purified antigen"
* $ICD11#XM5L44	" Tetanus vaccines"
* $ICD11#XM31Q8	" Tetanus, diphtheria, acellular pertussis"
* $ICD11#XM1LX9	" Diphtheria, hemophilus influenzae B, pertussis, poliomyelitis, tetanus vaccines"
* $ICD11#XM7JP3	" Diphtheria, hemophilus influenzae B, pertussis, tetanus, hepatitis B vaccines"
* $ICD11#XM5XP9	" Diphtheria, hemophilus influenzae B, pertussis, tetanus-hepatitis B, meningococcus A + C vaccines"
* $ICD11#XM41N3	" Diphtheria, hepatitis B, pertussis, tetanus vaccines"
* $ICD11#XM3G68	" Diphtheria, hepatitis B, tetanus vaccines"
* $ICD11#XM09Q7	" Diphtheria, pertussis, poliomyelitis, tetanus vaccines"
* $ICD11#XM0LT9	" Diphtheria, pertussis, poliomyelitis, tetanus, hepatitis B vaccines"
* $ICD11#XM8AW1	" Diphtheria, poliomyelitis, tetanus vaccines"
* $ICD11#XM84S1	" Diphtheria, hepatitis B, tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM9744	" Diphtheria, rubella, tetanus vaccines"
* $ICD11#XM29H5	" Tetanus toxoid vaccines"
* $ICD11#XM1G86	" Tetanus toxoid, combinations with diphtheria toxoid vaccines"
* $ICD11#XM9AK2	" Tetanus toxoid, combinations with tetanus immunoglobulin vaccines"
* $ICD11#XM21E6	" Diphtheria tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM32Q5	" Tetanus and diphtheria vaccines"
* $ICD11#XM9JP8	" Diphtheria, tetanus, acellular pertussis, inactivated polio virus vaccines"
* $ICD11#XM4039	" Vaccines diphtheria with tetanus"
* $ICD11#XM0RC1	" Encephalitis vaccines"
* $ICD11#XM8MP6	" Encephalitis, tick borne, inactivated, whole virus"
* $ICD11#XM8BU8	" Typhoid vaccines"
* $ICD11#XM3JA6	" Typhoid, hepatitis A vaccines"
* $ICD11#XM33K4	" Typhoid, oral, live attenuated vaccines"
* $ICD11#XM89G3	" Typhoid, inactivated, whole cell vaccines"
* $ICD11#XM3SF6	" Typhoid, purified polysaccharide antigen vaccines"
* $ICD11#XM9UB1	" Typhoid-paratyphoid vaccines"
* $ICD11#XM8DG3	" Varicella zoster vaccines"
* $ICD11#XM0NS8	" Varicella, live attenuated"
* $ICD11#XM0N24	" Yellow fever vaccine"
* $ICD11#XM3418	" Yellow fever, live attenuated"
* $ICD11#XM31Q8	" Tetanus, diphtheria, acellular pertussis vaccines"
* $ICD11#XM1LX9	" Diphtheria, hemophilus influenzae B, pertussis, poliomyelitis, tetanus vaccines"
* $ICD11#XM84S1	" Diphtheria, hepatitis B, tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM7JP3	" Diphtheria, hemophilus influenzae B, pertussis, tetanus, hepatitis B vaccines"
* $ICD11#XM5XP9	" Diphtheria, hemophilus influenzae B, pertussis, tetanus-hepatitis B, meningococcus A + C vaccines"
* $ICD11#XM41N3	" Diphtheria, hepatitis B, pertussis, tetanus vaccines"
* $ICD11#XM09Q7	" Diphtheria, pertussis, poliomyelitis, tetanus vaccines"
* $ICD11#XM0LT9	" Diphtheria, pertussis, poliomyelitis, tetanus, hepatitis B vaccines"
* $ICD11#XM1G86	" Tetanus toxoid, combinations with diphtheria toxoid vaccines"
* $ICD11#XM21E6	" Diphtheria tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM9JP8	" Diphtheria, tetanus, acellular pertussis, inactivated polio virus vaccines"
* $ICD11#XM32Q5	" Tetanus and diphtheria vaccines"
* $ICD11#XM4039	" Vaccines diphtheria with tetanus"
* $ICD11#XM32Q5	" Tetanus and diphtheria vaccines"
* $ICD11#XM4039	" Vaccines diphtheria with tetanus"
* $ICD11#XM1G86	" Tetanus toxoid, combinations with diphtheria toxoid vaccines"
* $ICD11#XM31Q8	" Tetanus, diphtheria, acellular pertussis vaccines"
* $ICD11#XM1LX9	" Diphtheria, hemophilus influenzae B, pertussis, poliomyelitis, tetanus vaccines"
* $ICD11#XM84S1	" Diphtheria, hepatitis B, tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM7JP3	" Diphtheria, hemophilus influenzae B, pertussis, tetanus, hepatitis B vaccines"
* $ICD11#XM5XP9	" Diphtheria, hemophilus influenzae B, pertussis, tetanus-hepatitis B, meningococcus A + C vaccines"
* $ICD11#XM41N3	" Diphtheria, hepatitis B, pertussis, tetanus vaccines"
* $ICD11#XM09Q7	" Diphtheria, pertussis, poliomyelitis, tetanus vaccines"
* $ICD11#XM0LT9	" Diphtheria, pertussis, poliomyelitis, tetanus, hepatitis B vaccines"
* $ICD11#XM21E6	" Diphtheria tetanus, acellular pertussis, inactivated polio virus, haemophilus Influenzae type B vaccines"
* $ICD11#XM9JP8	" Diphtheria, tetanus, acellular pertussis, inactivated polio virus vaccines"
* $ICD11#XM9744	" Diphtheria, rubella, tetanus vaccines"
* $ICD11#XM8AW1	" Diphtheria, poliomyelitis, tetanus vaccines"
* $ICD11#XM3G68	" Diphtheria, hepatitis B, tetanus vaccines"
* $ICD11#XM4039	" Vaccines diphtheria with tetanus"
* $ICD11#XM1G86	" Tetanus toxoid, combinations with diphtheria toxoid vaccines"
* $ICD11#XM38G7	" Dengue vaccine"
* $ICD11#XM68M6	" COVID-19 vaccines"
* $ICD11#XM0GQ8	" COVID-19 vaccine, RNA based"
* $ICD11#XM1NL1	" COVID-19 vaccine, inactivated virus"
* $ICD11#XM1J92	" COVID-19 vaccine, virus like particle"
* $ICD11#XM9QW8	" COVID-19 vaccine, non-replicating viral vector"
* $ICD11#XM6AT1	" COVID-19 vaccine, DNA based"
* $ICD11#XM5JC5	" COVID-19 vaccine, virus protein subunit"
* $ICD11#XM3CT4	" Recombinant SARS-CoV-2 vaccine"
* $ICD11#XM0CX4	" COVID-19 vaccine, replicating viral vector"
* $ICD11#XM5DF6	" COVID-19 vaccine, live attenuated virus"
* $ICD11#XM7JP3	" Diphtheria, hemophilus influenzae B, pertussis, tetanus, hepatitis B vaccines"